### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by Oushesh** [JuliaPoo/MultiHand-Tracking#4]
Hey Julia,
I am using tf version 1.8, python 3.6.8. 
I can import tensorflow.contrib.lite without errors but I cant import tensorflow.contrib.lite.interpreter.   

Which version tensorflow did you use?

**Comment by JuliaPoo** [comment]
Sorry for the late reply, I'm using tensorflow version 2.2.0, python 3.6.
